### ISSUE TITLE
Port changes when there is a path/port/scheme

### ISSUE THREAD

**Issue by ArtskydJ** [mafintosh/hostname-to-port#1]
``` js
var htp = require('hostname-to-port')

htp('example.com') // => 22019
htp('example.com/thing') // => 11319
htp('http://example.com') // => 49696
htp('example.com:80') // => 60351
```

If it's just the hostname, shouldn't these all return the same value?

**Comment by mafintosh** [comment]
Good point! I changed the name of the module to hash-to-port since it hashes any kind of value to a valid port. My primary use case was just hashing hostnames
